{
 "title": "Mssql",
 "tags": [ "mssql" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "instance",
    "query": "show tag values from sqlserver_performance with key = sql_instance"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Activity",
   "type": "graph",
   "description": ">sql errors:  监视 SQL Errors, _Total\n\nErrors/sec\n\n>database:    监视大容量复制操作、备份和还原吞吐量以及事务日志活动. _Total.\n\nWrite Transactions/sec\n\nTransactions/sec\n\nLog Flush Wait Time\n\nLog Flushes/sec\n\nLog Pool Requests/sec\n\nLog Pool Disk Reads/sec\n\nLog Pool Cache Misses/sec\n\n>locks: 提供了有关各种资源类型的 SQL Server 锁的信息, _Total.\n\nLock Timeouts/sec\n\nLock Waits/sec (=0)\n\nNumber of Deadlocks/sec (<1)\n\n>latches: 监视称为闩锁的内部 SQL Server 资源锁.\n\nLatch Waits/sec (<10)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM \"sqlserver_performance\" WHERE (\"sql_instance\" =~ /^$instance$/ AND \"instance\" = 'Total' AND \"counter\" = 'Errors/sec') AND $timeFilter GROUP BY time($__interval), \"sql_instance\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Errors/sec" }
     ]
    },
    {
     "alias": "Number of Deadlocks/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Number of Deadlocks/sec" }
     ]
    },
    {
     "alias": "Lock Waits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Waits/sec" }
     ]
    },
    {
     "alias": "Lock Timeouts/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Timeouts/sec" }
     ]
    },
    {
     "alias": "Latch Waits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Latch Waits/sec" }
     ]
    },
    {
     "alias": "Log Flushes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Flushes/sec" }
     ]
    },
    {
     "alias": "Log Flush Wait Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Flush Wait Time" }
     ]
    },
    {
     "alias": "Write Transactions/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Write Transactions/sec" }
     ]
    },
    {
     "alias": "Transactions/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Transactions/sec" }
     ]
    }
   ]
  },
  {
   "title": "SQL SERVER Activity",
   "type": "graph",
   "description": ">general statistics: 监视服务器范围内的常规活动.\n\nProcesses blocked(=0)\n\nLogins/sec\n\nLogouts/sec\n\nLogical/User Connections\n\n>sql statistics: 监视编译和发送到 SQL Server实例的请求类型.\n\nBatch Requests/sec\n\nSQL Compilations/sec (<10% up)\n\nSQL Re-Compilations/sec (<10% up)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "User Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    },
    {
     "alias": "Logins/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Logins/sec" }
     ]
    },
    {
     "alias": "Logouts/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Logouts/sec" }
     ]
    },
    {
     "alias": "SQL Compilations/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "SQL Compilations/sec" }
     ]
    },
    {
     "alias": "SQL Re-Compilations/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "SQL Re-Compilations/sec" }
     ]
    },
    {
     "alias": "Process blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Processes blocked" }
     ]
    },
    {
     "alias": "Batch Requests/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Batch Requests/sec" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "graph",
   "description": ">buffer manager: 监视对磁盘上的数据库页的物理访问.\n\nPage life expectancy\n\nLazy writes/sec (<20)\n\nCheckpoint pages/sec\n\nReadahead pages/sec\n\nPage lookups/sec\n\nPage reads/sec\n\nPage writes/sec\n\n>access methods: 监视如何访问数据库中的逻辑数据的计数器.\n\nFull Scans/sec \n\nIndex Searches/sec\n\nPage Splits/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Page life expectancy (Min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page life expectancy" }
     ]
    },
    {
     "alias": "Full Scans/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Full Scans/sec" }
     ]
    },
    {
     "alias": "Index Searches/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Index Searches/sec" }
     ]
    },
    {
     "alias": "Page Splits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page Splits/sec" }
     ]
    },
    {
     "alias": "Checkpoint pages/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Checkpoint pages/sec" }
     ]
    },
    {
     "alias": "Lazy writes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lazy writes/sec" }
     ]
    },
    {
     "alias": "Readahead pages/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Readahead pages/sec" }
     ]
    },
    {
     "alias": "Page life expectancy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page life expectancy" }
     ]
    },
    {
     "alias": "Page lookups/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page lookups/sec" }
     ]
    },
    {
     "alias": "Page reads/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page reads/sec" }
     ]
    },
    {
     "alias": "Page writes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page writes/sec" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "graph",
   "description": ">memory clerks: 实例中当前处于活动状态的全部内存分配器的集合。",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_clerk_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clerk_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait tasks count",
   "type": "graph",
   "description": ">wait task count: 该等待类型的总等待时间（毫秒）",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_category",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_category" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "waiting_tasks_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait time ms",
   "type": "graph",
   "description": ">wait time ms: 该等待类型的等待数",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_category",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_category" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Row read/write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "write/read" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Log  read/write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "write/read" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "write_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "LOG" }
     ]
    }
   ]
  }
 ]
}