{
 "title": "Rabbitmq",
 "tags": [ "rabbitmq" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "url",
    "query": "show tag values from rabbitmq_overview with key = url"
   }
  ]
 },
 "panels": [
  {
   "title": "Rabbitmq Overview",
   "type": "graph",
   "description": "Current total numbers for:\n\nconsumers\n\nchannels\n\nconnections\n\nexchanges\n\nqueues",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "query": "SELECT mean(\"consumers\") AS \"consumers\", mean(\"channels\") AS \"channels\", mean(\"connections\") AS \"connections\", mean(\"exchanges\") AS \"exchanges\", mean(\"queues\") AS \"queues\" FROM \"rabbitmq_overview\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "consumers" ], "type": "alias" }
      ],
      [
       { "params": [ "channels" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "channels" ], "type": "alias" }
      ],
      [
       { "params": [ "connections" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "connections" ], "type": "alias" }
      ],
      [
       { "params": [ "exchanges" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "exchanges" ], "type": "alias" }
      ],
      [
       { "params": [ "queues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "queues" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages Overview",
   "type": "graph",
   "description": "messages：处于未完成消费的状态的 消息总数。\n\nmessage ready:  处于等待被消费的状态的 消息数。\n\nmessage unack: 处于消费中状态的 消息数。",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_overview",
     "query": "SELECT mean(\"messages_unacked\") AS \"unack\", mean(\"messages_ready\") AS \"ready\", mean(\"messages\") AS \"messages\" FROM \"rabbitmq_overview\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "messages_unacked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "unack" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_ready" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ready" ], "type": "alias" }
      ],
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "messages" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Rate Overview",
   "type": "graph",
   "description": "Rate for:\n\nack\n\npublish\n\ndeliver\n\nredeliver",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "select": [
      [
       { "params": [ "messages_ack_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Ack" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_deliver_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Deliver" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_publish_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Publish" ], "type": "alias" }
      ],
      [
       { "params": [ "messages_redeliver_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "reDeliver" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "alias": "$tag_node",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "node" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_node",
     "query": "SELECT mean(\"running\") FROM \"rabbitmq_node\" WHERE $timeFilter GROUP BY time($__interval), \"node\" fill(none)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Ack rate for each queue.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "query": "SELECT mean(\"messages_ack_rate\") FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($__interval), \"queue\" fill(none)",
     "select": [
      [
       { "params": [ "messages_ack_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Publish rate for each queue.",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "query": "SELECT non_negative_derivative(mean(\"messages_publish\"), 1m) FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($__interval), \"queue\" fill(none)",
     "select": [
      [
       { "params": [ "messages_publish_rate" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Consumers for each queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "query": "SELECT mean(\"consumers\") FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($__interval), \"queue\" fill(none)",
     "select": [
      [
       { "params": [ "consumers" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  },
  {
   "title": "Messages for each queue",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_url:$tag_queue",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "queue" ], "type": "tag" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "rabbitmq_queue",
     "query": "SELECT mean(\"messages\") FROM \"rabbitmq_queue\" WHERE $timeFilter GROUP BY time($__interval), \"queue\" fill(none)",
     "select": [
      [
       { "params": [ "messages" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$url$/" }
     ]
    }
   ]
  }
 ]
}