{
 "title": "DBStat",
 "tags": [ "db" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "instance",
    "query": "show tag values from sqlserver_performance with key = sql_instance"
   }
  ]
 },
 "panels": [
  {
   "title": "Database Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Errors/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Errors/sec" }
     ]
    },
    {
     "alias": "Number of Deadlocks/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Number of Deadlocks/sec" }
     ]
    },
    {
     "alias": "Lock Waits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Waits/sec" }
     ]
    },
    {
     "alias": "Lock Timeouts/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lock Timeouts/sec" }
     ]
    },
    {
     "alias": "Latch Waits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Latch Waits/sec" }
     ]
    },
    {
     "alias": "Log Flushes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Flushes/sec" }
     ]
    },
    {
     "alias": "Log Flush Wait Time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Log Flush Wait Time" }
     ]
    },
    {
     "alias": "Write Transactions/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Write Transactions/sec" }
     ]
    },
    {
     "alias": "Transactions/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "sql_instance" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "Total" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Transactions/sec" }
     ]
    }
   ]
  },
  {
   "title": "SQL SERVER Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "User Connections",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "User Connections" }
     ]
    },
    {
     "alias": "Logins/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Logins/sec" }
     ]
    },
    {
     "alias": "Logouts/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Logouts/sec" }
     ]
    },
    {
     "alias": "SQL Compilations/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "SQL Compilations/sec" }
     ]
    },
    {
     "alias": "SQL Re-Compilations/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "SQL Re-Compilations/sec" }
     ]
    },
    {
     "alias": "Process blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Processes blocked" }
     ]
    },
    {
     "alias": "Batch Requests/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Batch Requests/sec" }
     ]
    }
   ]
  },
  {
   "title": "Buffer Manager",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Page life expectancy (Min)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page life expectancy" }
     ]
    },
    {
     "alias": "Full Scans/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Full Scans/sec" }
     ]
    },
    {
     "alias": "Index Searches/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Index Searches/sec" }
     ]
    },
    {
     "alias": "Page Splits/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Access Methods" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page Splits/sec" }
     ]
    },
    {
     "alias": "Checkpoint pages/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Checkpoint pages/sec" }
     ]
    },
    {
     "alias": "Lazy writes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Lazy writes/sec" }
     ]
    },
    {
     "alias": "Readahead pages/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Readahead pages/sec" }
     ]
    },
    {
     "alias": "Page life expectancy",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page life expectancy" }
     ]
    },
    {
     "alias": "Page lookups/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page lookups/sec" }
     ]
    },
    {
     "alias": "Page reads/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page reads/sec" }
     ]
    },
    {
     "alias": "Page writes/sec",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "object", "operator": "=", "value": "SQLServer:Buffer Manager" },
      { "condition": "AND", "key": "counter", "operator": "=", "value": "Page writes/sec" }
     ]
    }
   ]
  },
  {
   "title": "Memory Clerks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "kbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_clerk_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "clerk_type" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_memory_clerks",
     "select": [
      [
       { "params": [ "size_kb" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait tasks count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_category",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_category" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "waiting_tasks_count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Wait time ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_wait_category",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "wait_category" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_waitstats",
     "select": [
      [
       { "params": [ "wait_time_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Row read/write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "write/read" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ],
      [
       { "params": [ "write_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" }
     ]
    }
   ]
  },
  {
   "title": "Log  read/write Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "ms", "label": "write/read" }
   ],
   "targets": [
    {
     "alias": "$col:$tag_database_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "database_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sqlserver_database_io",
     "select": [
      [
       { "params": [ "write_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       { "params": [ "read_latency_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "sql_instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "file_type", "operator": "=", "value": "LOG" }
     ]
    }
   ]
  }
 ]
}